name: Check Week 7 Assignment
on:
  push:
    branches:
      - week9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Assignment
        working-directory: ./week9
        run: ./check
